name: qixi_mergers

services:
  admin:
    image: nginx:1.30.3-alpine3.23
    container_name: qixi_mergers_admin
    restart: unless-stopped
    env_file:
      - ./config/${QX_RELEASE_ENV:-local}/compose.env
    ports:
      - "${ADMIN_HOST_PORT:-18081}:80"
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      qixi_mergers_net:
        ipv4_address: 172.30.80.30

networks:
  qixi_mergers_net:
    external: true
    name: qixi_mergers_net
