/**
 * 平台侧栏可用 Lucide 图标（离线 bundle，见 scripts/build-iconify-offline.mjs）。
 * 新增菜单 icon 时同步改 SQL 种子与本列表，并运行 pnpm --filter @pte-live/admin-platform run build:icons
 */
export const PLATFORM_LUCIDE_ICON_NAMES = [
  'activity',
  'award',
  'badge',
  'badge-check',
  'badge-dollar-sign',
  'badge-percent',
  'badge-plus',
  'ban',
  'bar-chart-3',
  'bell',
  'boxes',
  'chart-area',
  'circle-dollar-sign',
  'circle-dot',
  'clipboard-list',
  'clipboard-pen',
  'contact',
  'contact-round',
  'credit-card',
  'database-backup',
  'eraser',
  'file-text',
  'folder-tree',
  'frame',
  'git-branch',
  'git-branch-plus',
  'hand-heart',
  'handshake',
  'hard-drive',
  'hash',
  'headphones',
  'headset',
  'heart-handshake',
  'history',
  'house',
  'images',
  'key-round',
  'landmark',
  'layers',
  'layout-dashboard',
  'layout-grid',
  'layout-template',
  'life-buoy',
  'list-tree',
  'log-in',
  'mail',
  'map-pinned',
  'map-plus',
  'medal',
  'megaphone',
  'menu',
  'message-circle',
  'message-circle-warning',
  'message-square',
  'message-square-reply',
  'messages-square',
  'monitor',
  'newspaper',
  'package',
  'paintbrush',
  'palette',
  'pen-line',
  'puzzle',
  'radio-tower',
  'receipt',
  'receipt-text',
  'scroll-text',
  'search',
  'send',
  'settings',
  'settings-2',
  'share-2',
  'shield',
  'shield-check',
  'shopping-bag',
  'smartphone',
  'sparkles',
  'store',
  'tags',
  'ticket',
  'ticket-check',
  'ticket-plus',
  'truck',
  'user-cog',
  'user-plus',
  'user-round',
  'user-round-cog',
  'users',
  'users-round',
  'wallet',
  'wallet-cards',
  'wrench',
] as const;

export const PLATFORM_LUCIDE_ICONS = PLATFORM_LUCIDE_ICON_NAMES.map(
  (name) => `lucide:${name}`,
);

/** 侧栏展示用：补全 lucide: 前缀，空值返回 undefined */
export function normalizePlatformMenuIcon(icon?: string) {
  const raw = String(icon || '').trim();
  if (!raw) {
    return undefined;
  }
  if (raw.includes(':')) {
    return raw;
  }
  return `lucide:${raw.replace(/^lucide-/, '')}`;
}
