<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { ElMessage } from 'element-plus';
import { getAccessCodesApi, getUserInfoApi } from '#/api/core/auth';
import { createRechargePlan, listRechargeOrders, listRechargePlans, updateRechargePlan, type RechargeOrder, type RechargePlan } from '#/api/core/platform-recharge';

const canManage=ref(false),rows=ref<RechargePlan[]>([]),orders=ref<RechargeOrder[]>([]),total=ref(0),open=ref(false),editing=ref<number>(),saving=ref(false);
const form=reactive({name:'',amount:0,bonus_amount:0,status:1,sort:0,version:0});
const query=reactive({page:1,limit:20,status:undefined as string|undefined});
async function load(){if(!canManage.value)return;const [plans,result]=await Promise.all([listRechargePlans(),listRechargeOrders(query)]);rows.value=plans.list||[];orders.value=result.list||[];total.value=result.total||0}
function edit(row?:RechargePlan){editing.value=row?.id;form.name=String(row?.name??'');form.amount=Number(row?.amount??0);form.bonus_amount=Number(row?.bonus_amount??0);form.status=Number(row?.status??1);form.sort=Number(row?.sort??0);form.version=Number(row?.version??0);open.value=true}
async function save(){if(!form.name.trim()||form.amount<=0||form.bonus_amount<0){ElMessage.warning('请填写计划名称和有效金额');return}saving.value=true;try{if(editing.value)await updateRechargePlan(editing.value,{...form});else await createRechargePlan({...form});ElMessage.success('充值计划已保存');open.value=false;await load()}finally{saving.value=false}}
onMounted(async()=>{const[p,c]=await Promise.all([getUserInfoApi(),getAccessCodesApi()]);canManage.value=p.roles.some(r=>r==='platform'||r==='operations')&&c.includes('marketing.recharge.manage');await load()});
</script>
<template><Page title="用户充值监管" description="维护可售充值计划，监管充值订单；后台不能改写已支付订单、支付回调或用户余额。"><el-alert v-if="!canManage" title="当前账号没有充值监管权限" type="warning" :closable="false"/><template v-else><el-card shadow="never"><template #header><div class="flex justify-between">充值计划<el-button type="primary" @click="edit()">新增计划</el-button></div></template><el-table :data="rows"><el-table-column prop="name" label="计划"/><el-table-column label="充值金额"><template #default="{row}">¥{{Number(row.amount).toFixed(2)}}</template></el-table-column><el-table-column label="赠送金额"><template #default="{row}">¥{{Number(row.bonus_amount).toFixed(2)}}</template></el-table-column><el-table-column label="状态"><template #default="{row}"><el-tag :type="row.status?'success':'info'">{{row.status?'启用':'停用'}}</el-tag></template></el-table-column><el-table-column prop="sort" label="排序"/><el-table-column label="操作"><template #default="{row}"><el-button link type="primary" @click="edit(row)">编辑</el-button></template></el-table-column></el-table></el-card><el-card class="mt-4" shadow="never"><template #header>充值订单（仅监管）</template><el-form inline><el-form-item label="状态"><el-select v-model="query.status" clearable><el-option label="待支付" value="pending"/><el-option label="已支付" value="paid"/><el-option label="已关闭" value="closed"/></el-select></el-form-item><el-button type="primary" @click="query.page=1;load()">查询</el-button></el-form><el-table :data="orders"><el-table-column prop="recharge_no" label="充值单号" min-width="180"/><el-table-column prop="user_id" label="用户 ID"/><el-table-column prop="amount" label="金额"/><el-table-column prop="bonus_amount" label="赠送"/><el-table-column prop="status" label="状态"/><el-table-column prop="created_at" label="创建时间" min-width="170"/></el-table></el-card><el-dialog v-model="open" :title="editing?'编辑充值计划':'新增充值计划'" width="480px" destroy-on-close><el-form label-width="100px"><el-form-item label="计划名称"><el-input v-model="form.name"/></el-form-item><el-form-item label="充值金额"><el-input-number v-model="form.amount" :min="0.01" :precision="2"/></el-form-item><el-form-item label="赠送金额"><el-input-number v-model="form.bonus_amount" :min="0" :precision="2"/></el-form-item><el-form-item label="状态"><el-radio-group v-model="form.status"><el-radio :value="1">启用</el-radio><el-radio :value="0">停用</el-radio></el-radio-group></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sort" :min="0"/></el-form-item></el-form><template #footer><el-button @click="open=false">取消</el-button><el-button :loading="saving" type="primary" @click="save">保存</el-button></template></el-dialog></template></Page></template>
