<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';

import { Page } from '@vben/common-ui';
import { ElMessage, ElMessageBox } from 'element-plus';
import ImagePickerDialog from '#/components/shop/image-picker-dialog.vue';
import type { AttachmentItem } from '#/api/core/attachment';

import { createVirtualProductComment, deleteVirtualProductComment, fetchProductComments, moderateProductComment, sortVirtualProductComment, updateVirtualProductComment, type ProductCommentRow, type ProductCommentStatus } from '#/api/core/ecrm';

const loading = ref(false); const dialog = ref(false); const saving = ref(false); const editing = ref<ProductCommentRow>();
const rows = ref<ProductCommentRow[]>([]); const total = ref(0);
const query = reactive({ page: 1, limit: 20, product_id: undefined as number | undefined, status: undefined as ProductCommentStatus | undefined });
const form = reactive({ product_id: undefined as number | undefined, score: 5, content: '', virtual_author_name: '', sort: 0, attachment_ids: undefined as number[] | undefined }); const picker = ref(false); const selectedImages = ref<AttachmentItem[]>([]);
const statusInfo = (status: ProductCommentStatus) => ({ pending: { label: '待审核', type: 'warning' as const }, published: { label: '已展示', type: 'success' as const }, hidden: { label: '已隐藏', type: 'info' as const } })[status];
const key = (action: string, id = 'new') => `comment-${action}-${id}-${crypto.randomUUID()}`;
function mediaUrls(raw: string) { try { const value = JSON.parse(raw); return Array.isArray(value) ? value.filter((url) => typeof url === 'string').slice(0, 9) : []; } catch { return []; } }

async function load() { loading.value = true; try { const data = await fetchProductComments({ ...query }); rows.value = data.list || []; total.value = data.total || 0; } finally { loading.value = false; } }
function search() { query.page = 1; void load(); }
function reset() { Object.assign(query, { page: 1, product_id: undefined, status: undefined }); void load(); }
function open(row?: ProductCommentRow) { editing.value = row; selectedImages.value=[]; Object.assign(form, row ? { product_id: row.product_id, score: row.score, content: row.content, virtual_author_name: row.virtual_author_name, sort: row.sort, attachment_ids: undefined } : { product_id: undefined, score: 5, content: '', virtual_author_name: '', sort: 0, attachment_ids: [] }); dialog.value = true; }
async function save() { if (!form.product_id || !form.content.trim() || !form.virtual_author_name.trim()) { ElMessage.warning('请填写商品 ID、显示昵称和评论内容'); return; } saving.value = true; try { const value={score:form.score,content:form.content.trim(),virtual_author_name:form.virtual_author_name.trim(),sort:form.sort,attachment_ids:form.attachment_ids}; if (editing.value) await updateVirtualProductComment(editing.value.id,{...value,idempotency_key:key('update',editing.value.id)}); else await createVirtualProductComment({product_id:form.product_id,...value,idempotency_key:key('create')}); dialog.value = false; ElMessage.success(editing.value ? '虚拟评论已更新' : '虚拟评论已新增并展示'); await load(); } finally { saving.value = false; } }
async function moderate(row: ProductCommentRow, action: 'hide' | 'publish') { const label = action === 'publish' ? '展示' : '隐藏'; try { const { value } = await ElMessageBox.prompt(`确认${label}该评论？可填写审核说明，用户原始评论不可篡改。`, `${label}评论`, { inputPlaceholder: '审核说明（可选，最多 500 字）', inputValidator: (value) => [...value].length <= 500 || '审核说明不能超过 500 字', confirmButtonText: `确认${label}`, cancelButtonText: '取消' }); await moderateProductComment(row.id, { action, note: value.trim(), idempotency_key: key(action, row.id) }); ElMessage.success(`评论已${label}`); await load(); } catch { /* 用户取消或统一请求层提示。 */ } }
async function sort(row: ProductCommentRow) { try { const { value } = await ElMessageBox.prompt('数值越大越靠前，仅影响虚拟评论展示顺序。', '调整排序', { inputValue: String(row.sort), inputPattern: /^\d{1,6}$/, inputErrorMessage: '请输入 0 到 999999 的整数', confirmButtonText: '保存', cancelButtonText: '取消' }); await sortVirtualProductComment(row.id, { sort: Number(value), idempotency_key: key('sort', row.id) }); ElMessage.success('排序已更新'); await load(); } catch { /* 用户取消或统一请求层提示。 */ } }
async function remove(row: ProductCommentRow) { try { const { value } = await ElMessageBox.prompt('删除仅对虚拟评论生效，将保留不可恢复的审核审计记录。', '删除虚拟评论', { inputPlaceholder: '删除说明（可选）', inputValidator: (value) => [...value].length <= 500 || '删除说明不能超过 500 字', confirmButtonText: '确认删除', cancelButtonText: '取消', type: 'warning' }); await deleteVirtualProductComment(row.id, { note: value.trim(), idempotency_key: key('delete', row.id) }); ElMessage.success('虚拟评论已删除'); await load(); } catch { /* 用户取消或统一请求层提示。 */ } }
onMounted(() => void load());
</script>

<template>
  <Page title="商品评论管理" description="真实评论仅审核展示状态；虚拟评论由平台创建、排序、编辑与软删除，所有操作保留审计记录。">
    <template #extra><el-button type="primary" @click="open()">新增虚拟评论</el-button></template>
    <el-card shadow="never"><el-form class="flex flex-wrap gap-x-4" label-width="76px" @submit.prevent="search"><el-form-item label="商品 ID"><el-input-number v-model="query.product_id" :min="1" controls-position="right" /></el-form-item><el-form-item label="展示状态"><el-select v-model="query.status" clearable placeholder="全部"><el-option label="待审核" value="pending" /><el-option label="已展示" value="published" /><el-option label="已隐藏" value="hidden" /></el-select></el-form-item><el-form-item><el-button type="primary" @click="search">查询</el-button><el-button @click="reset">重置</el-button></el-form-item></el-form></el-card>
    <el-card class="mt-4" shadow="never"><el-table v-loading="loading" :data="rows" row-key="id"><el-table-column label="ID" prop="id" width="82" /><el-table-column label="商品" min-width="190"><template #default="{ row }">{{ row.product_title || `商品 #${row.product_id}` }}<div class="text-xs text-gray-400">商品 #{{ row.product_id }} · 店铺 #{{ row.store_id }}</div></template></el-table-column><el-table-column label="来源" width="110"><template #default="{ row }"><el-tag :type="row.source === 'virtual' ? 'warning' : 'info'">{{ row.source === 'virtual' ? `虚拟：${row.virtual_author_name}` : '真实用户' }}</el-tag></template></el-table-column><el-table-column label="评分" width="100"><template #default="{ row }"><el-rate :model-value="row.score" disabled /></template></el-table-column><el-table-column label="评论内容" min-width="240" prop="content" show-overflow-tooltip /><el-table-column label="图片" width="120"><template #default="{ row }"><el-image v-for="url in mediaUrls(row.media)" :key="url" :src="url" fit="cover" class="mr-1 h-8 w-8" :preview-src-list="mediaUrls(row.media)" preview-teleported /><span v-if="!mediaUrls(row.media).length">—</span></template></el-table-column><el-table-column label="商家回复" min-width="150" prop="reply_content" show-overflow-tooltip /><el-table-column label="排序" width="80" prop="sort" /><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="statusInfo(row.status).type">{{ statusInfo(row.status).label }}</el-tag></template></el-table-column><el-table-column label="创建时间" min-width="170" prop="created_at" /><el-table-column fixed="right" label="操作" width="205"><template #default="{ row }"><el-button v-if="row.status !== 'published'" link type="success" @click="moderate(row, 'publish')">展示</el-button><el-button v-if="row.status !== 'hidden'" link type="warning" @click="moderate(row, 'hide')">隐藏</el-button><template v-if="row.source === 'virtual'"><el-button link type="primary" @click="open(row)">编辑</el-button><el-button link @click="sort(row)">排序</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></template></el-table-column></el-table><div class="mt-4 flex justify-end"><el-pagination :current-page="query.page" :page-size="query.limit" :page-sizes="[10, 20, 50, 100]" :total="total" background layout="total, sizes, prev, pager, next" @current-change="(page) => { query.page = page; load(); }" @size-change="(limit) => { query.limit = limit; query.page = 1; load(); }" /></div></el-card>
    <el-dialog v-model="dialog" :title="editing ? '编辑虚拟评论' : '新增虚拟评论'" width="560px" destroy-on-close><el-alert class="mb-4" type="warning" :closable="false" title="虚拟评论必须显著标识为虚拟来源；不得冒充真实用户或用于虚假交易宣传。" /><el-form label-width="90px"><el-form-item label="商品 ID" required><el-input-number v-model="form.product_id" :disabled="Boolean(editing)" :min="1" class="w-full" controls-position="right" /></el-form-item><el-form-item label="显示昵称" required><el-input v-model="form.virtual_author_name" maxlength="64" show-word-limit /></el-form-item><el-form-item label="评分" required><el-rate v-model="form.score" /></el-form-item><el-form-item label="评论内容" required><el-input v-model="form.content" type="textarea" :rows="4" maxlength="2000" show-word-limit /></el-form-item><el-form-item label="评论图片"><el-button @click="picker=true">从素材库选择（最多 9 张）</el-button><el-image v-for="image in selectedImages" :key="image.attachment_id" :src="image.attachment_src" class="ml-2 h-8 w-8" fit="cover" /></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sort" :min="0" :max="999999" controls-position="right" /></el-form-item></el-form><template #footer><el-button @click="dialog = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog><ImagePickerDialog v-model:open="picker" default-library="system" kind="image" :limit="9" @select="items=>{selectedImages=items;form.attachment_ids=items.map(item=>item.attachment_id)}" />
  </Page>
</template>
