<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { getAccessCodesApi, getUserInfoApi } from '#/api/core/auth';
import { listPlatformInvoices, type PlatformInvoice } from '#/api/core/platform-invoice';
const rows=ref<PlatformInvoice[]>([]), total=ref(0), loading=ref(false), canRead=ref(false);
const query=reactive({page:1,limit:20,status:undefined as PlatformInvoice['status']|undefined,order_no:''}); const labels:Record<PlatformInvoice['status'],string>={requested:'待开票',issued:'已开票',rejected:'已拒绝',voided:'已作废'};
async function load(){if(!canRead.value)return;loading.value=true;try{const r=await listPlatformInvoices({page:query.page,limit:query.limit,status:query.status,order_no:query.order_no.trim()||undefined});rows.value=r.list||[];total.value=r.total||0}finally{loading.value=false}}
function reset(){Object.assign(query,{page:1,status:undefined,order_no:''});void load()}
onMounted(async()=>{const[p,c]=await Promise.all([getUserInfoApi(),getAccessCodesApi()]);canRead.value=p.roles.includes('platform')&&c.includes('accounts.invoice.read');await load()});
</script>
<template><Page title="发票管理" description="只读监管订单发票申请与开具事实。税号、邮箱已脱敏；平台不能在此人工开票、改号、改文件、作废或删除。"><el-alert v-if="!canRead" title="当前账号没有发票监管权限" type="warning" :closable="false"/><template v-else><el-card shadow="never"><el-form inline @submit.prevent="query.page=1;load()"><el-form-item label="订单号"><el-input v-model="query.order_no" maxlength="64" clearable/></el-form-item><el-form-item label="状态"><el-select v-model="query.status" clearable class="w-28"><el-option v-for="(label,status) in labels" :key="status" :label="label" :value="status"/></el-select></el-form-item><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></el-form></el-card><el-card class="mt-4" shadow="never"><el-table v-loading="loading" :data="rows"><el-table-column prop="id" label="发票 ID" width="110"/><el-table-column prop="order_no" label="订单号" min-width="210"/><el-table-column label="店铺" min-width="180"><template #default="{row}">{{row.merchant_name}} / {{row.store_name}}</template></el-table-column><el-table-column prop="title" label="抬头" min-width="200"/><el-table-column prop="tax_no_masked" label="税号（脱敏）" min-width="160"/><el-table-column prop="email_masked" label="邮箱（脱敏）" min-width="180"/><el-table-column label="状态" width="110"><template #default="{row}"><el-tag>{{labels[row.status]}}</el-tag></template></el-table-column><el-table-column prop="invoice_no" label="发票号" min-width="180"/><el-table-column prop="requested_at" label="申请时间" min-width="180"/></el-table><div class="mt-4 flex justify-end"><el-pagination :current-page="query.page" :page-size="query.limit" :page-sizes="[10,20,50,100]" :total="total" background layout="total, sizes, prev, pager, next" @current-change="(p)=>{query.page=p;load()}" @size-change="(l)=>{query.limit=l;query.page=1;load()}"/></div></el-card></template></Page></template>
