<script setup lang="ts">
import { Page } from '@vben/common-ui';
import { ElMessage, ElMessageBox } from 'element-plus';
import { reactive, ref } from 'vue';
import type { MerchantCategory, MerchantCategoryInput } from '#/api/core/merchant-category';
import { createMerchantCategoryApi, deleteMerchantCategoryApi, listMerchantCategoriesApi, updateMerchantCategoryApi } from '#/api/core/merchant-category';
const rows = ref<MerchantCategory[]>([]), loading = ref(false), saving = ref(false), open = ref(false), editID = ref<number>();
const form = reactive<MerchantCategoryInput>({ parent_id: 0, name: '', sort: 0, status: 1 });
async function load() { loading.value = true; try { rows.value = (await listMerchantCategoriesApi()).list ?? []; } finally { loading.value = false; } }
function reset() { editID.value = undefined; Object.assign(form, { parent_id: 0, name: '', sort: 0, status: 1 }); }
function create() { reset(); open.value = true; }
function edit(row: MerchantCategory) { editID.value = row.category_id; Object.assign(form, { parent_id: row.parent_id, name: row.name, sort: row.sort, status: row.status }); open.value = true; }
async function save() { if (!form.name.trim()) { ElMessage.warning('请填写分类名称'); return; } saving.value = true; try { if (editID.value) await updateMerchantCategoryApi(editID.value, { ...form, name: form.name.trim() }); else await createMerchantCategoryApi({ ...form, name: form.name.trim() }); open.value = false; await load(); ElMessage.success('商品分类已保存'); } finally { saving.value = false; } }
async function changeStatus(row: MerchantCategory) { try { await updateMerchantCategoryApi(row.category_id, { parent_id: row.parent_id, name: row.name, sort: row.sort, status: row.status }); ElMessage.success('状态已更新'); } catch { await load(); } }
async function remove(row: MerchantCategory) { try { await ElMessageBox.confirm(`确定删除商品分类“${row.name}”吗？存在子分类或商品时将拒绝删除。`, '删除确认', { type: 'warning' }); await deleteMerchantCategoryApi(row.category_id); await load(); ElMessage.success('商品分类已删除'); } catch {} }
void load();
</script>
<template><Page title="商品分类" description="维护本店商品分类；分类与商品均按店铺隔离。"><template #extra><el-button type="primary" @click="create">新增分类</el-button></template><el-card shadow="never"><el-table v-loading="loading" :data="rows" row-key="category_id" default-expand-all><el-table-column prop="category_id" label="ID" width="80"/><el-table-column prop="name" label="分类名称" min-width="220"/><el-table-column prop="sort" label="排序" width="90"/><el-table-column label="启用" width="100"><template #default="{ row }"><el-switch v-model="row.status" :active-value="1" :inactive-value="0" @change="changeStatus(row)"/></template></el-table-column><el-table-column fixed="right" label="操作" width="130"><template #default="{ row }"><el-button link type="primary" @click="edit(row)">编辑</el-button><el-button link type="danger" @click="remove(row)">删除</el-button></template></el-table-column></el-table></el-card><el-dialog v-model="open" :title="editID ? '编辑商品分类' : '新增商品分类'" width="500px"><el-form label-width="88px"><el-form-item label="上级分类"><el-select v-model="form.parent_id" class="w-full"><el-option :value="0" label="顶级分类"/><el-option v-for="item in rows" :key="item.category_id" :value="item.category_id" :disabled="item.category_id === editID" :label="item.name"/></el-select></el-form-item><el-form-item label="分类名称" required><el-input v-model="form.name" maxlength="128"/></el-form-item><el-form-item label="排序"><el-input-number v-model="form.sort" :min="0"/></el-form-item><el-form-item label="启用"><el-switch v-model="form.status" :active-value="1" :inactive-value="0"/></el-form-item></el-form><template #footer><el-button @click="open = false">取消</el-button><el-button type="primary" :loading="saving" @click="save">保存</el-button></template></el-dialog></Page></template>
