name: qixi_mergers

services:
  api_app:
    image: alpine:3.24.1
    container_name: qixi_mergers_api_app
    restart: unless-stopped
    working_dir: /app
    env_file:
      - ./config/${QX_RELEASE_ENV:-local}/compose.env
    environment:
      TZ: Asia/Shanghai
    ports:
      - "${API_APP_HOST_PORT:-18085}:8080"
    volumes:
      - ./bin/api-app:/app/api-app:ro
      - ./config/${QX_RELEASE_ENV:-local}/app.yaml:/app/conf/app.yaml:ro
    command: ["/app/api-app", "-config", "/app/conf/app.yaml"]
    networks:
      qixi_mergers_net:
        ipv4_address: 172.30.80.22
      pte_live_net: {}

networks:
  qixi_mergers_net:
    external: true
    name: qixi_mergers_net
  pte_live_net:
    external: true
    name: pte_live_net
