<script setup lang="ts">
import { reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { ElMessage } from 'element-plus';
import { createPlatformUser } from '#/api/core/ecrm';
const submitting = ref(false);
const form = reactive({ account: '', password: '', confirm_password: '', nickname: '', reason: '' });
async function submit() { const account=form.account.trim(),nickname=form.nickname.trim(),reason=form.reason.trim(); if (account.length<3||account.length>191||nickname.length<1||nickname.length>64||form.password.length<12||form.password.length>72||form.password!==form.confirm_password||reason.length<2||reason.length>500) { ElMessage.warning('请填写账号、昵称、两次一致的 12 至 72 位密码及调整原因'); return; } submitting.value=true; try { const result=await createPlatformUser({account,password:form.password,nickname,reason,idempotency_key:`user-create-${crypto.randomUUID()}`}); ElMessage.success(`用户 #${result.user_id} 已创建；初始密码不会被再次显示`); Object.assign(form,{account:'',password:'',confirm_password:'',nickname:'',reason:''}); } finally { submitting.value=false; } }
</script>
<template><Page title="新增用户" description="仅平台角色可创建本地 PC 登录用户。密码只以 bcrypt 哈希保存，不会写入日志、审计、页面缓存或中文模拟数据。"><el-alert class="mb-4" type="warning" :closable="false" title="仅输入明显虚构的演示账号与临时密码。生产用户应通过受控身份注册流程创建。"/><el-card shadow="never" class="max-w-3xl"><el-form label-width="116px" @submit.prevent="submit"><el-form-item label="PC 登录账号" required><el-input v-model="form.account" maxlength="191" autocomplete="off" placeholder="例如：DEMO-PC-USER-9102"/></el-form-item><el-form-item label="用户昵称" required><el-input v-model="form.nickname" maxlength="64" placeholder="例如：七禧新客演示用户"/></el-form-item><el-form-item label="初始密码" required><el-input v-model="form.password" type="password" show-password autocomplete="new-password"/></el-form-item><el-form-item label="确认密码" required><el-input v-model="form.confirm_password" type="password" show-password autocomplete="new-password"/></el-form-item><el-form-item label="创建原因" required><el-input v-model="form.reason" type="textarea" :rows="4" maxlength="500" show-word-limit placeholder="例如：虚构中文验收工单，创建本地演示用户。"/></el-form-item><el-form-item><el-button type="primary" :loading="submitting" @click="submit">确认创建</el-button></el-form-item></el-form></el-card></Page></template>
