<script setup lang="ts">
import { reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { ElMessage } from 'element-plus';
import { sendPlatformUserInAppNotification } from '#/api/core/ecrm';
import UserRelationSelect from '#/components/ecrm/UserRelationSelect.vue';
const submitting=ref(false);const form=reactive({user_id:undefined as number|undefined,title:'',body:'',cover_url:'',reason:''});
async function submit(){const title=form.title.trim(),body=form.body.trim(),cover_url=form.cover_url.trim(),reason=form.reason.trim();if(!form.user_id||title.length<1||title.length>255||body.length<1||body.length>2000||!(cover_url===''||cover_url.startsWith('https://')||cover_url.startsWith('/demo/'))||reason.length<2||reason.length>500){ElMessage.warning('请填写用户、标题、正文、受控封面地址及调整原因');return}submitting.value=true;try{await sendPlatformUserInAppNotification(form.user_id,{title,body,cover_url,reason,idempotency_key:`user-notice-${form.user_id}-${crypto.randomUUID()}`});ElMessage.success('站内图文通知已创建并写入审计记录');Object.assign(form,{user_id:undefined,title:'',body:'',cover_url:'',reason:''})}finally{submitting.value=false}}
</script>
<template><Page title="用户站内图文通知" description="仅平台角色可发送 C 端站内图文通知。此页面不调用公众号、短信、邮件或 IM 外部通道，也不需要任何真实凭据。"><el-alert class="mb-4" type="info" :closable="false" title="封面仅允许 https:// 或 /demo/ 受控地址；留空即发送纯文本站内通知。外部微信图文必须经独立凭据投递服务验收。"/><el-card shadow="never" class="max-w-3xl"><el-form label-width="116px" @submit.prevent="submit"><el-form-item label="关联用户" required><UserRelationSelect v-model="form.user_id" /></el-form-item><el-form-item label="通知标题" required><el-input v-model="form.title" maxlength="255"/></el-form-item><el-form-item label="通知正文" required><el-input v-model="form.body" type="textarea" :rows="5" maxlength="2000" show-word-limit/></el-form-item><el-form-item label="封面地址"><el-input v-model="form.cover_url" maxlength="1024" placeholder="https:// 或 /demo/；可留空"/></el-form-item><el-form-item label="发送原因" required><el-input v-model="form.reason" type="textarea" :rows="4" maxlength="500" show-word-limit placeholder="例如：虚构中文服务工单，发送站内权益提醒。"/></el-form-item><el-form-item><el-button type="primary" :loading="submitting" @click="submit">确认发送</el-button></el-form-item></el-form></el-card></Page></template>
