<script setup lang="ts">
import { reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { ElMessage } from 'element-plus';
import { updatePlatformUserProfile } from '#/api/core/ecrm';
const submitting=ref(false); const form=reactive({user_id:undefined as number|undefined,nickname:'',avatar_url:'',gender:0 as 0|1|2,bio:'',reason:''});
async function submit(){const nickname=form.nickname.trim(),avatar_url=form.avatar_url.trim(),bio=form.bio.trim(),reason=form.reason.trim();if(!form.user_id||nickname.length<1||nickname.length>64||bio.length>500||!(avatar_url===''||avatar_url.startsWith('https://')||avatar_url.startsWith('/demo/'))||reason.length<2||reason.length>500){ElMessage.warning('请填写用户、昵称、受控头像地址和调整原因');return}submitting.value=true;try{await updatePlatformUserProfile(form.user_id,{nickname,avatar_url,gender:form.gender,bio,reason,idempotency_key:`user-profile-${form.user_id}-${crypto.randomUUID()}`});ElMessage.success('用户公开资料已保存并写入审计记录')}finally{submitting.value=false}}
</script>
<template><Page title="用户资料维护" description="仅平台角色可维护昵称、头像、性别和个人简介等公开资料；不编辑登录账号、手机、收货地址、证件或支付信息。"><el-card shadow="never" class="max-w-3xl"><el-form label-width="116px" @submit.prevent="submit"><el-form-item label="用户 ID" required><el-input-number v-model="form.user_id" :min="1"/></el-form-item><el-form-item label="用户昵称" required><el-input v-model="form.nickname" maxlength="64"/></el-form-item><el-form-item label="头像地址"><el-input v-model="form.avatar_url" maxlength="1024" placeholder="仅 https:// 或 /demo/ 资源"/></el-form-item><el-form-item label="性别"><el-radio-group v-model="form.gender"><el-radio :value="0">保密</el-radio><el-radio :value="1">男</el-radio><el-radio :value="2">女</el-radio></el-radio-group></el-form-item><el-form-item label="个人简介"><el-input v-model="form.bio" type="textarea" :rows="3" maxlength="500" show-word-limit/></el-form-item><el-form-item label="调整原因" required><el-input v-model="form.reason" type="textarea" :rows="4" maxlength="500" show-word-limit/></el-form-item><el-form-item><el-button type="primary" :loading="submitting" @click="submit">保存资料</el-button></el-form-item></el-form></el-card></Page></template>
