<script lang="ts" setup>
import type { VbenFormSchema } from '#/adapter/form';
import { computed, ref } from 'vue';
import { ElButton } from 'element-plus';
import DiyInputField from './shared/diy-input-field.vue';
import { diyColor, diyRadioGroup, diySection, diySlider } from './shared/schema-helpers';
import { useDiyCurItemForm } from './shared/use-diy-cur-item-form';
import { useDiyEditor } from './shared/use-diy-editor';
type RecordItem = Record<string, any>;
const props = defineProps<{ curItem: RecordItem & { params?: RecordItem; style?: RecordItem; data?: RecordItem[] } }>();
const tab = ref<'content' | 'style'>('content'); const editor = useDiyEditor();
function post(index: number) { return { title: ['把春天装进生活里', '像我这种乐形身材又怎样', '发现日常里的美好瞬间'][index] || '分享我的美好生活', author: ['浅笑回眸', '国宝小熊猫', '阿秋'][index] || '好物分享官', images: index + 3, image: '' }; }
function ensure(item: RecordItem) { const params = (item.params ??= {}); const style = (item.style ??= {}); Object.assign(params, { title: '种草社区', more: '好物分享', titleType: 'text', titleImage: '', layout: 'scroll', showNum: 3, showTitle: true, showAvatar: true, showAuthor: true, ...params }); Object.assign(style, { background: '#f5f5f5', cardBackground: '#ffffff', headStart: '#e93323', headEnd: '#ff7931', buttonColor: '#ffffff', buttonSize: 12, contentGap: 10, contentRadius: 8, contentShadow: 'off', paddingTop: 10, paddingBottom: 10, paddingLeft: 10, marginTop: 10, radius: 10, shadow: 'off', ...style }); if (!Array.isArray(item.data)) item.data = []; while (item.data.length < 6) item.data.push(post(item.data.length)); }
ensure(props.curItem); const params = computed(() => { ensure(props.curItem); return props.curItem.params!; }); const posts = computed(() => props.curItem.data ?? []);
const contentSchema = computed((): VbenFormSchema[] => [diySection('内容设置'), diyRadioGroup('params.titleType', '标题类型：', [{ label: '图片', value: 'image' }, { label: '文字', value: 'text' }]), diyRadioGroup('params.layout', '选择风格：', [{ label: '左右滑动展示', value: 'scroll' }, { label: '两列展示（纵向）', value: 'grid' }]), diySlider('params.showNum', '展示数量：', { min: 1, max: 6 }), diyRadioGroup('params.showTitle', '文章标题：', [{ label: '显示', value: true }, { label: '隐藏', value: false }]), diyRadioGroup('params.showAvatar', '作者头像：', [{ label: '显示', value: true }, { label: '隐藏', value: false }]), diyRadioGroup('params.showAuthor', '作者昵称：', [{ label: '显示', value: true }, { label: '隐藏', value: false }])]);
const styleSchema = computed((): VbenFormSchema[] => [diySection('头部样式'), diyColor('style.headStart', '背景颜色：', '#e93323'), diyColor('style.headEnd', '渐变终点：', '#ff7931'), diyColor('style.buttonColor', '按钮颜色：', '#ffffff'), diySlider('style.buttonSize', '按钮大小：', { min: 10, max: 24 }), diySection('内容样式'), diySlider('style.contentGap', '内容间距：', { min: 0, max: 32 }), diySlider('style.contentRadius', '内容圆角：', { min: 0, max: 32 }), diyRadioGroup('style.contentShadow', '开启阴影：', [{ label: '关闭', value: 'off' }, { label: '开启', value: 'on' }]), diySection('卡片样式'), diyColor('style.background', '底部背景：', '#f5f5f5'), diyColor('style.cardBackground', '组件背景：', '#ffffff'), diySlider('style.paddingTop', '上边距：', { min: 0, max: 48 }), diySlider('style.paddingBottom', '下边距：', { min: 0, max: 48 }), diySlider('style.paddingLeft', '左右边距：', { min: 0, max: 48 }), diySlider('style.marginTop', '页面上间距：', { min: 0, max: 48 }), diySlider('style.radius', '背景圆角：', { min: 0, max: 32 }), diyRadioGroup('style.shadow', '开启阴影：', [{ label: '关闭', value: 'off' }, { label: '开启', value: 'on' }])]);
const { Form: ContentForm } = useDiyCurItemForm(() => props.curItem, contentSchema, { onInit: ensure }); const { Form: StyleForm } = useDiyCurItemForm(() => props.curItem, styleSchema, { onInit: ensure });
</script>
<template><div class="community-params"><div class="common-form common-form-new"><span>{{ curItem.name }}</span><div class="diy-changes"><div class="diy-change" :class="{ active: tab === 'content' }" @click="tab = 'content'">内容</div><div class="diy-change" :class="{ active: tab === 'style' }" @click="tab = 'style'">样式</div></div></div><div v-show="tab === 'content'"><ContentForm /><section class="community-param-section"><h4>头部设置</h4><label v-if="params.titleType === 'text'"><span>标题文字</span><DiyInputField v-model="params.title" :maxlength="8" /></label><div v-else class="community-image"><img v-img-url="params.titleImage" alt="标题图片" @click="editor.onEditorSelectImage(params, 'titleImage')" /><ElButton link type="primary" @click="params.titleImage = ''">重置</ElButton><small>建议尺寸 128px × 32px</small></div><label><span>右侧按钮</span><DiyInputField v-model="params.more" :maxlength="6" /></label></section><section class="community-param-section"><h4>文章内容</h4><div v-for="(post, index) in posts" :key="index" class="post-editor"><DiyInputField v-model="post.title" :maxlength="22" /><DiyInputField v-model="post.author" :maxlength="10" /><ElButton plain size="small" @click="editor.onEditorSelectImage(post, 'image')">选择封面</ElButton></div></section></div><div v-show="tab === 'style'"><StyleForm /></div></div></template>
<style scoped>.community-param-section { margin: 12px 0; padding: 12px; border-radius: 8px; background: #f7f8fa; }.community-param-section h4 { margin: 0 0 10px; font-size: 14px; }.community-param-section label { display: flex; align-items: center; gap: 10px; margin-top: 8px; }.community-param-section label span { width: 68px; color: #606266; font-size: 13px; }.community-image { display: flex; flex-wrap: wrap; align-items: center; gap: 8px; }.community-image img { width: 128px; height: 32px; background: #fff; object-fit: contain; }.community-image small { width: 100%; color: #909399; }.post-editor { display: grid; grid-template-columns: 1fr 1fr; gap: 7px; margin-top: 8px; }.post-editor :deep(.el-button) { grid-column: span 2; }</style>
