name: qixi_mergers

services:
  job:
    image: alpine:3.24.1
    container_name: qixi_mergers_job
    restart: unless-stopped
    working_dir: /app
    env_file:
      - ./config/${QX_RELEASE_ENV:-local}/compose.env
    environment:
      TZ: Asia/Shanghai
    volumes:
      - ./bin/job:/app/job:ro
      - ./config/${QX_RELEASE_ENV:-local}/app.yaml:/app/conf/app.yaml:ro
    command: ["/app/job", "-config", "/app/conf/app.yaml"]
    networks:
      qixi_mergers_net:
        ipv4_address: 172.30.80.21
      pte_live_net: {}

networks:
  qixi_mergers_net:
    external: true
    name: qixi_mergers_net
  pte_live_net:
    external: true
    name: pte_live_net
