<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue';
import { Page } from '@vben/common-ui';
import { getAccessCodesApi, getUserInfoApi } from '#/api/core/auth';
import { listPlatformLoginLogs, type PlatformLoginLog } from '#/api/core/platform-operation-log';
const rows=ref<PlatformLoginLog[]>([]),total=ref(0),loading=ref(false),canRead=ref(false);const query=reactive({page:1,limit:20,username:'',success:undefined as 0|1|undefined,dates:[] as string[]});
async function load(){if(!canRead.value)return;loading.value=true;try{const r=await listPlatformLoginLogs({page:query.page,limit:query.limit,username:query.username.trim()||undefined,success:query.success,start_date:query.dates[0],end_date:query.dates[1]});rows.value=r.list||[];total.value=r.total||0}finally{loading.value=false}}
function reset(){Object.assign(query,{page:1,username:'',success:undefined,dates:[]});void load()}onMounted(async()=>{const[p,c]=await Promise.all([getUserInfoApi(),getAccessCodesApi()]);canRead.value=p.roles.includes('platform')&&c.includes('setting.operation_log.read');await load()});
</script>
<template><Page title="登录日志" description="只读展示统一后台登录结果。日志不含密码、令牌或请求体；仅平台安全审计账号可查看。"><el-alert v-if="!canRead" title="当前账号没有登录日志查看权限" type="warning" :closable="false"/><template v-else><el-card shadow="never"><el-form inline @submit.prevent="query.page=1;load()"><el-form-item label="账号"><el-input v-model="query.username" maxlength="64" clearable/></el-form-item><el-form-item label="结果"><el-select v-model="query.success" clearable class="w-28"><el-option label="成功" :value="1"/><el-option label="失败" :value="0"/></el-select></el-form-item><el-form-item label="日期"><el-date-picker v-model="query.dates" type="daterange" value-format="YYYY-MM-DD" range-separator="至" start-placeholder="开始日期" end-placeholder="结束日期"/></el-form-item><el-button type="primary" @click="query.page=1;load()">查询</el-button><el-button @click="reset">重置</el-button></el-form></el-card><el-card class="mt-4" shadow="never"><el-table v-loading="loading" :data="rows"><el-table-column prop="id" label="日志 ID" width="100"/><el-table-column prop="admin_user_id" label="管理员 ID" width="120"/><el-table-column prop="username" label="账号" min-width="160"/><el-table-column prop="role_code" label="角色" width="130"/><el-table-column label="结果" width="100"><template #default="{row}"><el-tag :type="row.success?'success':'danger'">{{row.success?'成功':'失败'}}</el-tag></template></el-table-column><el-table-column prop="ip" label="IP" width="150"/><el-table-column prop="user_agent" label="客户端标识" min-width="220" show-overflow-tooltip/><el-table-column prop="created_at" label="时间" min-width="180"/></el-table><div class="mt-4 flex justify-end"><el-pagination :current-page="query.page" :page-size="query.limit" :page-sizes="[10,20,50,100]" :total="total" background layout="total, sizes, prev, pager, next" @current-change="(p)=>{query.page=p;load()}" @size-change="(l)=>{query.limit=l;query.page=1;load()}"/></div></el-card></template></Page></template>
