const PATH_COMPONENT: Record<string, string> = {
  '/dashboard': 'mergers/dashboard/index',
  '/config/freight/shippingTemplates': 'mergers/shipping/templates',
  '/product/label': 'mergers/product/label',
  '/product/specs': 'mergers/product/specs',
  '/product/attr': 'mergers/product/specs',
  '/config/guarantee': 'mergers/product/guarantee',
  '/order/invoice': 'mergers/order/invoice',
  '/order/list': 'mergers/order/list',
  '/order/refund': 'mergers/order/refund',
  '/product/list': 'mergers/product/list',
  '/finance/balance': 'mergers/finance/balance',
  '/finance/withdraw': 'mergers/finance/withdraw',
  '/marketing/coupon': 'mergers/marketing/coupon',
  '/marketing/coupon/list': 'mergers/marketing/coupon',
  '/marketing/coupon/send': 'mergers/marketing/coupon-records',
  '/marketing/coupon/user': 'mergers/marketing/coupon-records',
  '/marketing/seckill/list': 'mergers/marketing/seckill',
  '/marketing/seckill/product/list': 'mergers/marketing/seckill',
  '/marketing/seckill/store_seckill/list': 'mergers/marketing/seckill',
  '/marketing/presell/list': 'mergers/marketing/presell',
  '/marketing/broadcast': 'mergers/marketing/broadcast',
  '/marketing/studio/list': 'mergers/marketing/broadcast',
  '/marketing/broadcast/list': 'mergers/marketing/broadcast',
  '/marketing/community': 'mergers/marketing/community',
  '/community/list': 'mergers/marketing/community',
  '/setting/shop': 'mergers/setting/shop',
  '/setting/staff': 'mergers/setting/staff',
  '/setting/admins': 'mergers/setting/admins',
  '/setting/role': 'mergers/setting/role',
  '/setting/payment': 'mergers/setting/payment',
  '/setting/im-sdk-app': 'mergers/setting/im-sdk-app',
  '/setting/attachment': 'mergers/setting/attachment',
  '/config/picture': 'mergers/setting/attachment',
  '/devise/diy/list': 'mergers/diy/list',
  '/devise/diy/index': 'mergers/diy/editor',
};

export function resolveMergersComponent(path: string): string | undefined {
  const normalized = path.startsWith('/') ? path : `/${path}`;
  return PATH_COMPONENT[normalized];
}
